image: alekzonder/puppeteer:latest

before_script:
  - npm install
  - mkdir -p universe_frontend/
  - wget --quiet -o universe_frontend/dist.zip https://gitlab.com/creators-of-the-universe/universe_frontend/-/jobs/artifacts/master/download?job=build
  - node node_modules/onezip/bin/onezip.js -x $(pwd)/universe_frontend/dist.zip
test:
  script:
    - npm run test

